### ISSUE TITLE
urql instead of fetchql

### ISSUE THREAD

**Issue by frederikhors** [pateketrueke/svql#3]
@pateketrueke, your work with Svelte 3 is amazing (yrv).

I would like to see your brain struggling with https://github.com/FormidableLabs/urql.

I think fetchql is a zombie project.

What do you think about?

**Comment by pateketrueke** [comment]
IMHO svql is just a wrapper over basic graphql+fetch and urql is an advanced client.

I just wanted the lightest graphql component to fulfill my requirements, and it does it. :beers:
