### ISSUE TITLE
saved session not automatically used by created client

### ISSUE THREAD

**Issue by stellanhaglund** [pateketrueke/svql#7]
Hi! I tried out your package which is very nice.
Though I have a problem where I need to call useClient or setupClient again after saveSession, otherwise the same session token is used even though a new one in placed in the localStorage.
Is this intended?

**Comment by pateketrueke** [comment]
> Is this intended?

I don't think so, is just a side-effect, I believe we could fix that!

Let me see what I need to fix this, thank you.
