### ISSUE TITLE
repl pokemon not found

### ISSUE THREAD

**Issue by markfirmware** [pateketrueke/svql#8]

**Comment by pateketrueke** [comment]
Yeah, I've noticed that earlier but I did not updated the demo — the API I was using is down, so I'll need to upgrade or change the example, thank you!

**Comment by markfirmware** [comment]
Thanks.

**Comment by pateketrueke** [comment]
Solved by https://github.com/lucasbento/graphql-pokemon/issues/15#issuecomment-690120620
